name: court_craze
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  country_picker: ^2.0.23
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  url_launcher: ^6.2.4
  youtube_data_api_vk:
    path: packages/youtube_data_api_vk
  http: ^0.13.6
  shared_preferences: ^2.2.3
  line_icons: ^2.0.3
  pod_player: ^0.2.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/images/
  
