// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3W7ii-yvBJxZtvVRFYNPIJnevmt0IKEg',
    appId: '1:150776766204:web:25b5355c91f01aa10b4179',
    messagingSenderId: '150776766204',
    projectId: 'electric-signal-423715-i1',
    authDomain: 'electric-signal-423715-i1.firebaseapp.com',
    storageBucket: 'electric-signal-423715-i1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0nVXMsXu6Nx11Y0rzAgtfebt22sw4TI8',
    appId: '1:150776766204:android:5725305c0adc3a0c0b4179',
    messagingSenderId: '150776766204',
    projectId: 'electric-signal-423715-i1',
    storageBucket: 'electric-signal-423715-i1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnj2SlLQSKzPFPNpyN00oai9TBB1KyJjY',
    appId: '1:150776766204:ios:c7e7d266bdfccfd90b4179',
    messagingSenderId: '150776766204',
    projectId: 'electric-signal-423715-i1',
    storageBucket: 'electric-signal-423715-i1.appspot.com',
    iosBundleId: 'com.example.courtCraze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnj2SlLQSKzPFPNpyN00oai9TBB1KyJjY',
    appId: '1:150776766204:ios:c7e7d266bdfccfd90b4179',
    messagingSenderId: '150776766204',
    projectId: 'electric-signal-423715-i1',
    storageBucket: 'electric-signal-423715-i1.appspot.com',
    iosBundleId: 'com.example.courtCraze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3W7ii-yvBJxZtvVRFYNPIJnevmt0IKEg',
    appId: '1:150776766204:web:15bdf47dcf7ea5150b4179',
    messagingSenderId: '150776766204',
    projectId: 'electric-signal-423715-i1',
    authDomain: 'electric-signal-423715-i1.firebaseapp.com',
    storageBucket: 'electric-signal-423715-i1.appspot.com',
  );
}
